// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl-QJO6sdcF_XJHkjYqRzdqHEqFPKUrRo',
    appId: '1:650789426501:web:6cae69bf9a4e24d7c51a2c',
    messagingSenderId: '650789426501',
    projectId: 'myprofile-7ebb9',
    authDomain: 'myprofile-7ebb9.firebaseapp.com',
    storageBucket: 'myprofile-7ebb9.firebasestorage.app',
    measurementId: 'G-0MEKY3CPYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWzBuHNoadwMK85qg1Yz-EfBxTWyN8Lc',
    appId: '1:650789426501:android:d3e6ea8922107071c51a2c',
    messagingSenderId: '650789426501',
    projectId: 'myprofile-7ebb9',
    storageBucket: 'myprofile-7ebb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXHl0dhYbgxwXxh22D7hWyQOyLC2kstbg',
    appId: '1:650789426501:ios:d2127d2f1e09af4dc51a2c',
    messagingSenderId: '650789426501',
    projectId: 'myprofile-7ebb9',
    storageBucket: 'myprofile-7ebb9.firebasestorage.app',
    iosBundleId: 'com.mosalahportofolio.myportofolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXHl0dhYbgxwXxh22D7hWyQOyLC2kstbg',
    appId: '1:650789426501:ios:d2127d2f1e09af4dc51a2c',
    messagingSenderId: '650789426501',
    projectId: 'myprofile-7ebb9',
    storageBucket: 'myprofile-7ebb9.firebasestorage.app',
    iosBundleId: 'com.mosalahportofolio.myportofolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl-QJO6sdcF_XJHkjYqRzdqHEqFPKUrRo',
    appId: '1:650789426501:web:483107b3febff8aac51a2c',
    messagingSenderId: '650789426501',
    projectId: 'myprofile-7ebb9',
    authDomain: 'myprofile-7ebb9.firebaseapp.com',
    storageBucket: 'myprofile-7ebb9.firebasestorage.app',
    measurementId: 'G-C0PPZZT4L4',
  );
}
